### ISSUE TITLE
Notifications > Allow customers to enable/disable notification types

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#3203]
## Story

As a customer, I want to be able to enable or disable notification types, so that I can control which notifications are sent to members on my site.

## Scope

Full scope of project covered in this Loom:
https://www.loom.com/share/3c62fa1d2acc4c05871695ed9c10456a

Wireframes:
https://miro.com/app/board/o9J_l_f8wxM=/?invite_link_id=453709154265
pw: buddyboss

We want to add an "Automatic Notifications" metabox to BuddyBoss Platform > Settings > Notifications. It can go above the "On-Screen Notifications" metabox. 

<img width="717" alt="Screenshot 2021-11-24 at 16 36 15" src="https://user-images.githubusercontent.com/75724470/143330013-4b0842ae-1360-4cd3-8b6a-4ea079f6c711.png">

This should be done after we've improved the way BuddyBoss notification types are registered (see [this issue](https://github.com/buddyboss/buddyboss-platform/issues/3205))

When a BuddyBoss notification type is registered, it should automatically appear in these settings.

If a customer disabled a notification, it will never be generated and won't show on the "Notifications Preferences" screen (see [this issue](https://github.com/buddyboss/buddyboss-platform/issues/3204)).

## Acceptance Criteria

- [x] An "Automatic Notifications" metabox shows in BuddyBoss Platform > Settings > Notifications
- [ ] All [registered notification types](https://github.com/buddyboss/buddyboss-platform/issues/3205) show in the metabox
- [ ] If a customer disabled a notification, it is not generated for members and doesn't show on the "Notifications Preferences" screen (see [this issue](https://github.com/buddyboss/buddyboss-platform/issues/3204)).

## Issues in "Improve Notifications" Epic

**BuddyBoss Platform**

- https://github.com/buddyboss/buddyboss-platform/issues/3205
- https://github.com/buddyboss/buddyboss-platform/issues/3203
- https://github.com/buddyboss/buddyboss-platform/issues/3204

**BuddyBoss App**

- https://github.com/buddyboss/buddyboss-app/issues/2566
- https://github.com/buddyboss/buddyboss-app-native/issues/1829
- https://github.com/buddyboss/buddyboss-app-native/issues/1847

**Jira issue** : [PROD-676]

[PROD-676]: https://buddyboss.atlassian.net/browse/PROD-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by sourabhmatolia** [comment]
@mikejyoung 

Nicely explained. I have got few concerns:
https://www.loom.com/share/4bbb1cc355f141e086fb73c2d927bbe1

**Comment by sourabhmatolia** [comment]
@mikejyoung 

Further concern we have based on discussion with Hardip.
Please check video:
https://www.loom.com/share/5f37fbc7f58240dbb8b6dd0ddc4324f5

**Comment by singhleo** [comment]
I have a suggestion we should use an abstract class as API for registering notifications. so we can make strict rules on how to do the extends. we can use the hooks and everything internally but won't recommend the users to use them directly.

CC @mikejyoung @chetansatasiya @KartikSuthar @sourabhmatolia

**Comment by sourabhmatolia** [comment]
@mikey

Sorry got further concerns after reviewing what we discussed on Friday:
https://www.loom.com/share/8caf69b29968435a8581a6857168643a

**Comment by mikey** [comment]
@sourabhmatolia wrong @mikey think

**Comment by sourabhmatolia** [comment]
Based on discussion with Team, here's clarification on concerns shared above:

**Check Video:**
https://www.loom.com/share/3cb3fbdc742e440d8e4a6a15df3feadb

@chetansatasiya @KartikSuthar Please take note of Platform related changes
@parmarhardip @janakkaneriya007 App Plugin related changes 
@shakilAshraful  App Native related changes

**Comment by mikejyoung** [comment]
@chetansatasiya @KartikSuthar 
Updated scope for all the issues:
https://www.loom.com/share/b0bc3881ef284b12971288199f2de58f?from_recorder=1&focus_title=1

I will create new scope, Loom and criteria for each individual issue tomorrow.

CC: @firozwp @sourabhmatolia
