### ISSUE TITLE
Notifications > Create a "Notification Preferences" screen (Web)

### ISSUE THREAD

**Issue by mikejyoung** [buddyboss/buddyboss-platform#3204]
**NOTE TO DEVELOPERS**
We are currently having full UI designs completed for this issue. For now, you can start by following the wireframes. I will update this issue when designs when ready.

------

## Story

As a member, I want to be able to manage which notification are sent to my devices, so I can control how often I get notified.

## Scope

Full scope of project covered in this Loom:
https://www.loom.com/share/3c62fa1d2acc4c05871695ed9c10456a

Wireframes:
https://miro.com/app/board/o9J_l_f8wxM=/?invite_link_id=453709154265
pw: buddyboss

We want to change the "Email Preferences" screen to "Notification Preferences", to add support for members managing which notifications are sent as:

- Email
- Desktop (web push notifications / on-screen notifications)
- Mobile (app push notifications)

A member can disable all notifications for a device type, or manage notifications by type.

## Acceptance Criteria

- [x] The "Email Preferences" screen in "Account Settings" is renamed to "Notification Preferences"
- [ ] The screen is laid out as wireframes
- [ ] All [registered notifications](https://github.com/buddyboss/buddyboss-platform/issues/3205) that are [enabled](https://github.com/buddyboss/buddyboss-platform/issues/3203), shows on the screen
- [ ] If a device is disabled in the "Enable Notifications" section, all corresponding notifications for that device type are disabled (but previous options are preserved)
- [ ] When all notifications are disabled for a device type, no notifications to send to those type of devices
- [ ] When a notification type is disabled for a device type, it does not send to those type of devices device
- [ ] If the "Notifications" component is disabled, the "Notification Preferences" screen shows a list of email situations that can be enabled/disabled by the member

## Issues in "Improve Notifications" Epic

**BuddyBoss Platform**

- https://github.com/buddyboss/buddyboss-platform/issues/3205
- https://github.com/buddyboss/buddyboss-platform/issues/3203
- https://github.com/buddyboss/buddyboss-platform/issues/3204

**BuddyBoss App**

- https://github.com/buddyboss/buddyboss-app/issues/2566
- https://github.com/buddyboss/buddyboss-app-native/issues/1829
- https://github.com/buddyboss/buddyboss-app-native/issues/1847

**Jira issue** : [PROD-675]

[PROD-675]: https://buddyboss.atlassian.net/browse/PROD-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mikejyoung** [comment]
@chetansatasiya @KartikSuthar 
Updated scope for all the issues:
https://www.loom.com/share/b0bc3881ef284b12971288199f2de58f?from_recorder=1&focus_title=1

I will create new scope, Loom and criteria for each individual issue tomorrow.

CC: @firozwp @sourabhmatolia
